#!/usr/bin/env ruby

# https://dl.dropbox.com/u/39519/talks/tok-workflow/index.html#11
file="~/.gitshots/#{Time.now.to_i}.jpg"
puts "Taking capture into #{file}!"
system "imagesnap -q -w 3 #{file}"
exit 0
